// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC90eg3312evO5gPOh8SBuEp7dt53Xwqwo',
    appId: '1:104006379494:web:efd55c10ea80379d2e5827',
    messagingSenderId: '104006379494',
    projectId: 'nasa-tlx',
    authDomain: 'nasa-tlx.firebaseapp.com',
    databaseURL: 'https://nasa-tlx.firebaseio.com',
    storageBucket: 'nasa-tlx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADkwIZ7ImI79v4mvJPzWhb8CKvz-KdDyg',
    appId: '1:104006379494:android:016fad486890c41b2e5827',
    messagingSenderId: '104006379494',
    projectId: 'nasa-tlx',
    databaseURL: 'https://nasa-tlx.firebaseio.com',
    storageBucket: 'nasa-tlx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlxqkuXnkuaNKj0mE9ABHcso620JsyA4M',
    appId: '1:104006379494:ios:1d85bcd3da8464992e5827',
    messagingSenderId: '104006379494',
    projectId: 'nasa-tlx',
    databaseURL: 'https://nasa-tlx.firebaseio.com',
    storageBucket: 'nasa-tlx.appspot.com',
    androidClientId: '104006379494-cjopo8om8piib093darm58gl8dd35sa7.apps.googleusercontent.com',
    iosClientId: '104006379494-ogvlukq2ls6ve562304gueh661klu2ih.apps.googleusercontent.com',
    iosBundleId: 'com.cookie-gone-cuckoo.nasa-tlx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlxqkuXnkuaNKj0mE9ABHcso620JsyA4M',
    appId: '1:104006379494:ios:1d85bcd3da8464992e5827',
    messagingSenderId: '104006379494',
    projectId: 'nasa-tlx',
    databaseURL: 'https://nasa-tlx.firebaseio.com',
    storageBucket: 'nasa-tlx.appspot.com',
    androidClientId: '104006379494-cjopo8om8piib093darm58gl8dd35sa7.apps.googleusercontent.com',
    iosClientId: '104006379494-ogvlukq2ls6ve562304gueh661klu2ih.apps.googleusercontent.com',
    iosBundleId: 'com.cookie-gone-cuckoo.nasa-tlx',
  );
}
